### PR TITLE
Eliminate use of Object.assign. Fixes #142

### LINKED ISSUE #142: Object.assign crashes IE 11
My Next.js app keeps crashing in IE 11, and upon investigation I found out that the source of the issue was a direct call to `Object.assign` inside of `valuesToParams`.

It appears that there is an _extends function added for use of the object spread operator. Updating the statements to use the spread operator in place of `Object.assign` might be the simplest solution.

### PR DESCRIPTION
**Pull request by fritz-c**
When the bundle was created by babel, calls to Object.assign were being
left as-is, causing errors in IE 11 that left the user staring at a
blank screen.

Fixes #142

### CODE REVIEW

**Comment by fridays** [comment]
Thanks for contributing! I think it should be taken care of by `next/babel`. Do you use a custom babel file, and can you check if it's happening too with only a bare Next.js project?

**Comment by fritz-c** [comment]
I wasn't using a custom babel file.
Here is an minimal reproduction repo: https://github.com/fritz-c/next-routes-ie

**Comment by fritz-c** [comment]
I suppose the issue with `next/babel` could be traced back to one of these changes: https://github.com/zeit/next.js/commits/ebf0c47c25541cfc50c8f319141f4bc9f47daeb8/server/build/babel/preset.js

**Comment by stevokk** [comment]
I am seeing the same issue in IE11, and my custom babel file is below: (I need it for the test framework)

```
{
    "env": {
      "development": {
        "presets": ["next/babel"]
      },
      "production": {
        "presets": ["next/babel"]
      },
      "test": {
        "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]]
      }
    }
  }
```

Including a polyfill in my Layout component works for now but isn't optimal.

**Comment by jonjamz** [comment]
As stated in the Next.js docs, you should handle polyfills yourself. There is an example showing how to do it. See:

https://github.com/zeit/next.js#browser-support

Perhaps a warning in the docs would suffice?

**Comment by stevokk** [comment]
If we can easily switch out Object.assign and avoid babel configuration issues with no additional ongoing maintenance I'd argue that it makes sense? I'd forgotten I added the polyfill but this is something I'll be coming back to resolve soon, whether it be with babel or a fork of this repo.

**Comment by oliviertassinari** [comment]
Has anyone released a fork without the usage of `Object.assign`? This method isn't supported by IE 11 (~2% of traffic) and Chrome 41 (googlebot!).

**Pull request closed without merging**
