### PR TITLE
add typescript typings

### PR DESCRIPTION
**Pull request by disintegrator**
Hey there. Thanks for the awesome library. It's saving us a lot of time and guesswork. I'm currently using it with my own declarations in my project. I thought it'd be a good idea to send you PR to add a declaration file into this package so you can publish types alongside the code.

### CODE REVIEW

**Comment by fridays** [comment]
Awesome! I never used typescript but several people asked for this, thank you!

**Comment by disintegrator** [comment]
yay! thank you @fridays :)
Please feel free to ping me if you make changes to the API. I can try to keep the typings up to date.

**Comment by fridays** [comment]
Great, thanks for the support!

**Comment by smkhalsa** [comment]
@disintegrator Considering that the default server.js needs to use require, not import, statements and therefore routes.ts also would not be allowed to use import statements, are you using type assertions for routes.js imports in your client code?

An example project would be helpful. Thanks!

**Comment by brandonmp** [comment]
@smkhalsa  server.js doesn't need to use require. there's an [example in the next repo](https://github.com/zeit/next.js/tree/canary/examples/custom-server-typescript) that uses a separate `tsconfig.json` to build `server.ts`, _then_ run the app


@disintegrator  is the default export typing correct? the [default export line ](https://github.com/fridays/next-routes/blob/master/src/index.js#L7) is `module.exports = opts => new Routes(opts)`, but the default [export type ](https://github.com/fridays/next-routes/blob/master/typings/next-routes.d.ts)is a `export default class Routes implements Registry {...`

I'm still new w/ TS, but only asking b/c my IDE is yelling at me about this code: 

```
import makeRoutes from 'next-routes';
const routes = makeRoutes({ Link });
```

yields:
```
Value of type 'typeof Routes' is not callable. Did you mean to include 'new'?
```

**Comment by KevinBusch** [comment]
☝️ like @brandonmp said, the typing file doesn't appear to be right here.  This library deafult export is returning a new instance of the class... not the class itself.

**Comment by naorye** [comment]
@KevinBusch a pull request has been created (https://github.com/fridays/next-routes/pull/333).

**Comment by arminops** [comment]
@disintegrator How should i implement your changes them in my project??? using `next-routes` and `next v8.1` .

**Pull request merged**
